# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: beman-tidy lint, testing and installing

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' #  08:00AM EEST (@neatudarius' timezone) -> 05:00AM UTC

jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/beman-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment
        run: |
          uv sync

      - name: Run linter
        run: |
          uv run ruff check --diff

      - name: Run tests
        run: |
          uv run pytest tests/ -v

  build_and_install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/beman-tidy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment
        run: |
          uv sync

      - name: Build and install beman-tidy
        run: |
         uv clean
         uv build
         python3 -m pip install dist/beman_tidy-0.1.0-py3-none-any.whl --force-reinstall
         beman-tidy --help

      - name: Run installed beman-tidy on exemplar repo
        run: |
          git clone https://github.com/bemanproject/exemplar.git
          cd exemplar/ # Testing that beman-tidy can be run from any path, e.g. from the exemplar repo.
          beman-tidy --verbose --require-all .

  create-issue-when-fault:
    needs: [run_tests, build_and_install]
    if: failure() && github.event.schedule == '0 5 * * *' # 08:00AM EEST (@neatudarius' timezone) -> 05:00AM UTC
    uses: ./.github/workflows/reusable-beman-create-issue-when-fault.yml