# SPDX-License-Identifier: 2.0 license with LLVM exceptions
name: Publish Beman devcontainers

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DEBUG_IMAGE_NAME: ${{ github.repository }}
  DEPLOY_IMAGE_NAME: beman/devcontainers

permissions:
  packages: write

jobs:
  build-and-push-devcontainer-image:
    runs-on: ubuntu-latest
    name: Update devcontainer
    steps:
      - name: Compute Tag
        id: tag
        run:
          image_name=${{ env.DEPLOY_IMAGE_NAME }}
          if [ "${{ github.repository_owner }}" != "beman" ]; then
              image_name=${{ env.DEBUG_IMAGE_NAME }}
          fi
          tag=${{ env.REGISTRY }}/$image_name:gcc-14
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: devcontainer
          build-args: |
            gnu_version=14
          push: true
          tags: ${{ steps.tag.outputs.tag }}
